### ISSUE TITLE
css-module's :global syntax?

### ISSUE THREAD

**Issue by yoshuawuyts** [shama/attach-css#1]
I initially rejected `:global`, but after having read [an article](https://medium.com/seek-ui-engineering/the-end-of-global-css-90d2a4a06284) and seen the [css-modules org](https://github.com/css-modules/css-modules) 'm changing my mind. Is the `:global` syntax something that should be adopted, and what are the steps to do so?
### example

``` css
.foo {
  font-size: 2rem;
}

/* exported globally */
:global .foo {
  color: green;
}
```
